SET IDENTITY_INSERT [dbo].[Travailleur] ON
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (2, N'Renard', N'Maxime', N'Chaussée d''Arlon', CAST(15 AS Decimal(3, 0)), N'Marloie', CAST(6900 AS Decimal(4, 0)), CAST(1 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (3, N'Willot', N'Kevin', N'Rue des Orfèvres', CAST(7 AS Decimal(3, 0)), N'Dinant', CAST(5500 AS Decimal(4, 0)), CAST(2 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (4, N'Keymolen', N'Andrew', N'Rue petite', CAST(10 AS Decimal(3, 0)), N'Marloie', CAST(6900 AS Decimal(4, 0)), CAST(3 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (5, N'Vancutsem', N'Justin', N'Rue grande', CAST(7 AS Decimal(3, 0)), N'Marche', CAST(6900 AS Decimal(4, 0)), CAST(4 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (6, N'Kecira', N'Salim', N'Rue plate', CAST(2 AS Decimal(3, 0)), N'Namur', CAST(5000 AS Decimal(4, 0)), CAST(5 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (7, N'Willot', N'Jose', N'Avenue Charlemagne', CAST(16 AS Decimal(3, 0)), N'Liege', CAST(4000 AS Decimal(4, 0)), CAST(6 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (8, N'Mercken', N'Thierry', N'Boulevard des grands', CAST(105 AS Decimal(3, 0)), N'Bruxelles', CAST(1000 AS Decimal(4, 0)), CAST(7 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (9, N'Miroult', N'Quantin', N'Avenue des combattants', CAST(6 AS Decimal(3, 0)), N'Anhee', CAST(5537 AS Decimal(4, 0)), CAST(8 AS Decimal(6, 0)))
INSERT INTO [dbo].[Travailleur] ([idTravailleur], [nom], [prenom], [adr_rue], [adr_numero], [adr_localite], [adr_codePostal], [numDossier]) VALUES (10, N'Repere', N'Cedric', N'Quai Culot', CAST(15 AS Decimal(3, 0)), N'Dinant', CAST(5500 AS Decimal(4, 0)), NULL)
SET IDENTITY_INSERT [dbo].[Travailleur] OFF
