SET IDENTITY_INSERT [dbo].[Ris_Exa] ON
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (2, 1, 1)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (3, 1, 2)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (4, 1, 3)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (5, 1, 5)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (6, 1, 8)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (7, 1, 9)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (8, 2, 1)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (9, 2, 2)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (10, 2, 3)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (11, 2, 5)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (12, 2, 9)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (13, 3, 1)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (14, 3, 2)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (16, 3, 3)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (17, 3, 5)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (18, 3, 9)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (19, 4, 1)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (20, 4, 2)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (21, 4, 3)
INSERT INTO [dbo].[Ris_Exa] ([idRisqueExamen], [idRisque], [idExamen]) VALUES (22, 5, 6)
SET IDENTITY_INSERT [dbo].[Ris_Exa] OFF
