INSERT INTO [dbo].[Profession] ([idProfession]) VALUES (N'EL1')
INSERT INTO [dbo].[Profession] ([idProfession]) VALUES (N'SO2')
INSERT INTO [dbo].[Profession] ([idProfession]) VALUES (N'MA3')
INSERT INTO [dbo].[Profession] ([idProfession]) VALUES (N'GA4')
INSERT INTO [dbo].[Profession] ([idProfession]) VALUES (N'IF5')
